### ISSUE TITLE
Improve period selection on report viewer

### ISSUE THREAD

**Issue by jotegui** [VertNet/usagestats#5]
Now that there are 20+ reports on each resource page, it can be tedious having to scroll down to check older reports. Maybe we could add a dropdown list as a separate option for selecting the period to view.

**Comment by tucotuco** [comment]
Not sure. With a dropdown you can't do a CNTRL-F or Command -F to search on
the web page, no?

**Comment by jotegui** [comment]
You're right, that's why I thought adding, and not replacing, could be
helpful. But if it isn't a problem, I'm happy to skip this one.

## 

Javier Otegui
http://www.jotegui.com

**Comment by tucotuco** [comment]
I think skip it. Low priority.
